apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-deployment
  namespace: lanchonete
  labels:
    app: lanchonete
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lanchonete
  template:
    metadata:
      labels:
        app: lanchonete
    spec:
      containers:
        - name: lanchonete
          image: lanchonete:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db:3306/lanchonete?allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root