apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: lanchonete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: your-admin-image:latest
          ports:
            - containerPort: 3000