apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: lanchonete
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: payment-image:latest
          ports:
            - containerPort: 8081