apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: lanchonete
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP